name: release

on:
  release:
    types: [published]

jobs:
  release-binaries:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: obsidian-garden
            asset_name: obsidian-garden-linux-amd64
          - os: macos-latest
            artifact_name: obsidian-garden
            asset_name: obsidian-garden-macos-amd64

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  release-default-template:
    name: Publish default template
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: zip -r default-template.zip templates/default

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: default-template.zip
        tag: ${{ github.ref }}