name: release

on:
  push:
    branches:
      - release-static-binaries
  release:
    types: [published]

jobs:
  release-binaries:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Install cargo-rs
      shell: bash
      run: |
        cargo install cross

    - name: Build
      run: cross build --target ${{ matrix.target }} --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.target }}/release/obsidian-garden
        asset_name: obsidian-garden-${{ matrix.target}}
        tag: ${{ github.ref }}

  release-default-template:
    name: Publish default template
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: zip -r default-template.zip templates/default

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: default-template.zip
        tag: ${{ github.ref }}